name: 'Self-Test'

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test-job:
    uses: './.github/workflows/test.yml'
