name: 'Self-Test'

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test-job:
    # @see https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
    uses: './.github/workflows/test-coverage.yml'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
