name: 'Test'

on:
  workflow_call:

jobs:
  test-job:
    if: |
      contains(github.event.commits[0].message, '[skip ci]') == false &&
      contains(github.event.commits[0].message, '[ci skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
      - name: 'Run tests on clean install'
        run: |
          npm ci
          npm test
