name: 'Test & Coverage'

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: 'Coverage Upload Token: https://docs.codecov.com/docs/codecov-uploader#upload-token'
        required: false
jobs:
  test-coverage:
    if: |
      contains(github.event.commits[0].message, '[skip ci]') == false &&
      contains(github.event.commits[0].message, '[ci skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: 'Run tests on clean install'
        run: |
          yarn install --frozen-lockfile
          yarn test
      - name: 'Upload code coverage from "main" branch'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          files: ./coverage/lcov.info
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false
        if: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' }}
